ls /shipdata/en484/r2r/eventlog/elog/elogd.cfg
ls /shipdata/en487/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC462/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC467/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC468-02/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-06/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-06/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-12/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-12/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-13/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-13/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-14/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN200-02/r2r/eventlog/elog/elogd.cfg
ls /shipdata/CH0511/r2r/eventlog/elog/elogd.cfg
ls /shipdata/CH0511/r2r/eventlog/elog/elogd.cfg
ls /shipdata/EN494/r2r/eventlog/elog/elogd.cfg
ls /shipdata/EN494/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC471-04/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC471-04/r2r/eventlog/elog/elogd.cfg
ls /shipdata/SS00001/r2r/eventlog/elog/elogd.cfg
ls /shipdata/MV1108/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC473/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC475/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC475/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC476-01/r2r/eventlog/elog/elogd.cfg
ls /shipdata/TN268/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AE1211/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-18/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT18-18/r2r/eventlog/elog/elogd.cfg
ls /shipdata/MGL1211/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC1206A/r2r/eventlog/elog/elogd.cfg
ls /shipdata/EN502/r2r/eventlog/elog/elogd.cfg
ls /shipdata/EN513/r2r/eventlog/elog/elogd.cfg
ls /shipdata/EN520/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN207-01/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN207-02/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN207-03/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN209-01/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT19/r2r/eventlog/elog/elogd.cfg
ls /shipdata/AT19/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN205/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN205/r2r/eventlog/elog/elogd.cfg
ls /shipdata/MV1206/r2r/eventlog/elog/elogd.cfg
ls /shipdata/NH1208/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC1209A/r2r/eventlog/elog/elogd.cfg
ls /shipdata/at25/r2r/eventlog/elog/elogd.cfg
ls /shipdata/at26-01/r2r/eventlog/elog/elogd.cfg
ls /shipdata/at26-02/r2r/eventlog/elog/elogd.cfg
ls /shipdata/at26-04/r2r/eventlog/elog/elogd.cfg
ls /shipdata/en524/r2r/eventlog/elog/elogd.cfg
ls /shipdata/en527/r2r/eventlog/elog/elogd.cfg
ls /shipdata/KN210-04/r2r/eventlog/elog/elogd.cfg
ls /shipdata/MGL1305/r2r/eventlog/elog/elogd.cfg
ls /shipdata/PS1306/r2r/eventlog/elog/elogd.cfg
ls /shipdata/oc1307c/r2r/eventlog/elog/elogd.cfg
ls /shipdata/OC1308A/r2r/eventlog/elog/elogd.cfg
ls /shipdata/oc1308B/r2r/eventlog/elog/elogd.cfg
ls /shipdata/RR1301/r2r/eventlog/elog/elogd.cfg
ls /shipdata/tn299/r2r/eventlog/elog/elogd.cfg
